services:

  ollama-backend:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./services/ollama:/root/.ollama
      - ./zscaler_cert:/tmp/zscaler_cert
    container_name: ollama-backend
    networks:
      - gsa-gov

  chromadb:
    image: chromadb/chroma:0.6.2
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./services/chroma:/chroma/chroma
    networks:
      - gsa-gov

  ollama-openweb-ui:
    image: ghcr.io/open-webui/open-webui:dev
    ports:
      - "3000:8080"
    volumes:
      - ./services/openweb-ui:/openweb-ui
    environment:
      - OLLAMA_API_BASE_URL=http://ollama-backend:11434/api
    depends_on:
      - ollama-backend
    container_name: ollama-openweb-ui
    networks:
      - gsa-gov

networks:
  gsa-gov:
