services:

  nginx-cert-gen:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx-cert-gen:/etc/nginx/conf.d
    container_name: nginx-cert-gen
    networks:
      - gsa-gov

networks:
  gsa-gov:
