services:
  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/chroma/chroma
    restart: always
    networks:
      - gsa-gov
    
  ollama-backend:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    container_name: ollama-backend
    networks:
      - gsa-gov

  ollama-openweb-ui:
    image: ghcr.io/open-webui/open-webui:dev
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama-backend:11434/api
    depends_on:
      - ollama-backend
    restart: always
    container_name: ollama-openweb-ui
    networks:
      - gsa-gov

networks:
  gsa-gov:
