services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    container_name: nginx
    networks:
      - gsa-gov

networks:
  gsa-gov:
