services:
  proxy:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./services/proxy/data:/data
      - ./services/proxy/letsencrypt:/etc/letsencrypt
    networks:
      - gsa-gov

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./services/ollama:/root/.ollama
      - ./zscaler_cert:/tmp/zscaler_cert
    expose:
      - "${OLLAMA_EXPSPORT}"
    environment:
      VIRTUAL_HOST:  ${OLLAMA_HOSTNAME}
      WEB_PORTS: "${OLLAMA_HOSTPORT}"
    networks:
      - gsa-gov

  chroma:
    image: chromadb/chroma:0.6.2
    container_name: chroma
    restart: unless-stopped
    volumes:
      - ./services/chroma:/chroma/chroma
    expose:
      - "${CHROMA_EXPSPORT}"
    environment:
      VIRTUAL_HOST:  ${CHROMA_HOSTNAME}
      WEB_PORTS: ${CHROMA_HOSTPORT}
    networks:
      - gsa-gov

  openweb:
    image: ghcr.io/open-webui/open-webui:dev
    container_name: openweb
    restart: unless-stopped
    volumes:
      - ./services/openweb:/openweb-ui
    expose:
      - ${OPENUI_EXPSPORT}
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - VIRTUAL_HOST=${OPENUI_HOSTNAME}
      - VIRTUAL_PORT=${OPENUI_HOSTPORT}
    depends_on:
      - ollama
    networks:
      - gsa-gov

networks:
  gsa-gov:
